### ISSUE TITLE
Top workflow not working for me

### ISSUE THREAD

**Issue by ianrobertdouglas** [jinkunw/alfred-workflows#1]
Hi. I installed this workflow as normal, but it doesn't appear if I type "top" in Alfred. I'm wondering what I'm doing wrong.

**Comment by jinkunw** [comment]
Can you enable the debugging mode in Top workflow page and paste the output?

**Comment by ianrobertdouglas** [comment]
Sure. All it says is: Starting debug for 'Top'
Zero else.

**Comment by jinkunw** [comment]
Did you change the log type to "All information"?

**Comment by ianrobertdouglas** [comment]
Both return the same.

**Comment by jinkunw** [comment]
It seems to me that your workflow is not triggered. Can you run the command `python top.py` in the top workflow folder in terminal to see if the script works correctly?

**Comment by ianrobertdouglas** [comment]
hmm. I get: python: can't open file 'top.py': [Errno 2] No such file or directory

**Comment by jinkunw** [comment]
You don't work in the right directory. Right-click the top workflow and you can show the top folder in your Finder by selecting `Show in Finder`. Go to that directory, then run the command again.

**Comment by ianrobertdouglas** [comment]
Sorry about that. It seems to work running it from the directory. But not from Alfred. It doesn't even appear in my options when I type "top". Title case makes no difference.

**Comment by jinkunw** [comment]
I hope you don't forget to check `Enable` in the right-click menu.

**Comment by ianrobertdouglas** [comment]
I didn't change anything, but checking that I can see it is ticked "Enabled", so that's no the issue.

**Comment by ianrobertdouglas** [comment]
I mean that the workflow was enabled, is enabled, and doesn't work.

**Comment by jinkunw** [comment]
Change the script of top from `python top.py` to `echo "top triggered"`. If you still see nothing in the debugging mode, then I can't help you.
